services:
  - type: web
    name: channel-forward-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: YOUR_API_ID
      - key: API_HASH
        value: YOUR_API_HASH
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN
      - key: OWNER_ID
        value: YOUR_TELEGRAM_USER_ID
